### ISSUE TITLE
Transformations - advisory or mandated?

### ISSUE THREAD

**Issue by lovelydinosaur** [core-api/core-api#12]
Should link transition types _indicate the expected transform_, or _enforce_ it?
Eg. If a "delete" link returns a document, should that be an error or should a replace transform be effected?
Currently the specification uses the "enforce" style, but the python client library uses the "indicate" style.

**Comment by phalt** [comment]
I'd go with enforcing it, as we're trying to encourage a standard format here. Unless this effects only the transport method, in which case we should let the internals of that decide? So long as it is enforced on the representation / document, it can be agnostic of what's happening elsewhere?

**Comment by lovelydinosaur** [comment]
> I'd go with enforcing it

Yes, I think so too.

I've been going with a style where the `Document` specification is strict, but the `Encoding` and `Transport` specifications are lenient. The implication of that would be that:
- The document layer _MUST_ expect the indicated return types.
- The transport layer _SHOULD_ expect the indicated return types, and _MAY_ coerce them to the expected type in the event of failure. (Eg. a "delete" transition that returns content may be ignored by the transport layer, returning `null`.)

Given that we'll fail hard if we can't parse the content, it seems reasonable to also fail hard if we _don't_ receive content when it was expected.

**Comment by phalt** [comment]
I like this, it allows non-traditional or obscure transports methods to be implemented.

**Comment by lovelydinosaur** [comment]
No longer relevant now that we have separate `action` and `transform` indicators instead of `transition`.
`transform="inplace"`will remove the document if no content is returned, or update it if it is, so we don't have this case to worry about anymore.
