### ISSUE TITLE
Add refresh transition type

### ISSUE THREAD

**Issue by lovelydinosaur** [core-api/core-api#14]
Safe, idempotent operation, that replaces the document.
Won't typically be used in a link itself, but provided by the client library as an implicitly available transition on any document.

**Comment by phalt** [comment]
How would the client know that the copy of the document they have is out of date? Could the refresh transition provide a means of detecting is a refresh is needed? datetime stamps etc?

**Comment by lovelydinosaur** [comment]
Possibly, as part of the document timestamp/etag info (see the todo list on the readme) but nothing currently planned.

Right now this is just about recognising a valid transition type that's not currently represented, and making it easier for clients to implement a .refresh method in a way that's consistent with regular transitions.
