### ISSUE TITLE
json-ld as hypermedia description language?

### ISSUE THREAD

**Issue by auvipy** [core-api/core-api#20]

**Comment by lovelydinosaur** [comment]
Closing as this is not a substantive or actionable issue.

**Comment by auvipy** [comment]
What do you think about having a 3rd party package name drf-jsonld/drf-hypermedia[with different types of definition language json-ld,raml etc] for drf?

**Comment by lovelydinosaur** [comment]
No problem whatsoever with folks writing third party hypermedia packages for REST framework, tho that's not related to this project.
