### ISSUE TITLE
Meaning

### ISSUE THREAD

**Issue by mcintyre321** [core-api/core-api#45]
Hi. I've just been reading up on Core API, (which looks great) and it overlaps lot of the goals I am trying to achieve in a work-in-progress hypermedia server project of my own, bar (I think) one aspect. 

In my "document layer" equivalent, I have an additional constraint, which is that rather than keys being string values, I am enforcing that they are URLs which dereference to a resource describing the "meaning" of that key. This way a client can be coded to consume a known set of keys, and can ignore* keys it does not understand. Similar to what JSON-LD achieves with it's `@context`.

Is there (or could there be) a facility in Core API for providing meanings in-band with documents? 

*or otherwise handle in another way (e.g. by alerting the client developer, or loading some code on demand, )

**Comment by lovelydinosaur** [comment]
A 'rel' attribute might exist at some point in the future, yup.
