### ISSUE TITLE
Towards Response Schemas: adding `Field` read-only/write-only attributes

### ISSUE THREAD

**Issue by carltongibson** [core-api/core-api#51]
Ref https://github.com/encode/django-rest-framework/issues/4502

I've been thinking about the adjustments needed to provide Response Schemas in Django REST Framework. 

This breaks down into two-layers: 

* The actual Core API Schema
* The work done by renderers to present that. 

**At the Core API level** I believe the minimal change we need here — or at least the minimal change for a first step — is to an enumeration based property to `Field` with three possible states: 

1. `read_only`
2. `write_only` 
3. Not present, or `read-write` (if preferred)

With this we have a simple heuristic for when to present the field: 

* If it is `read_only`, the field is part of the response (schema). 
* If it is `write_only` the fields is part of the request (schema).
* Otherwise the field is part of both. 

**At the Core API level** this single change would suffice. In the **renderer** — e.g. for Django REST Framework's Interactive Documentation, and others — we would likely present the field list in separate "Request" and "Response" sections (with `read-write` fields being duplicated **at the point where they were rendered** in both sections).

**Comment by antwan** [comment]
In addition, I think it would be nice to indicate what's the expected format for each field (string, integer, date, whatever)

**Comment by lovelydinosaur** [comment]
We'll want to have an explicit response schema, rather than re-purposing the existing fields as read/write. The read/write idea would work well for CRUD but isn't general purpose enough.

We'll want to use something like either `response_schema`, or perhaps a whole new `response` section on the `Link`.
