### ISSUE TITLE
Design api docs

### ISSUE THREAD

**Issue by bergran** [core-api/core-api#55]
Hello guys! i come from django rest framework to report a minor bug.

This bug consist when you have a lot of endpoints, the `Authentication`  section and `source code` section is up of endpoints and you can not scroll more, could you move those sections to other site or fix this?

This sections are locate fixed on left-bottom.

![captura de pantalla 2018-02-05 a las 15 11 41](https://user-images.githubusercontent.com/30236379/35808704-f293a3ce-0a86-11e8-8692-e6aab5585d5c.png)

**Comment by lovelydinosaur** [comment]
Thanks! Probably better to take this to REST framework, since that's where the docs generation happens.
