### ISSUE TITLE
Improve docs to indicate the CoreAPI will be phased out

### ISSUE THREAD

**Issue by johnthagen** [core-api/core-api#58]
From https://www.django-rest-framework.org/community/3.9-announcement/#whats-next 

> We're planning to iteratively work towards OpenAPI becoming the standard schema representation. This will mean that the `coreapi` dependency will gradually become removed, and we'll instead generate the schema directly, rather than building a CoreAPI `Document` object.

Being new to the DRF it took me a while to discover that for a new project I **shouldn't** consider using CoreAPI as it seems like a dead end. It would really be helpful if this repo clearly noted this in the README.

Would you accept a PR?

**Comment by lovelydinosaur** [comment]
> Would you accept a PR

Sure thing
