### ISSUE TITLE
Link specification.

### ISSUE THREAD

**Issue by lovelydinosaur** [core-api/core-api#7]
Specify what information links have associated with them. `url`, `type`, `fields`.
Specify transition types.
Specify fields.
Specify valid parameters when calling a link. Primitives, documents, file upload.

| type | transition | safe | idempotent |
| --- | --- | --- | --- |
| "follow" | new | ✓ | ✓ |
| "action" | replace | ✗ | ✗ |
| "create" | new | ✗ | ✗ |
| "update" | replace | ✗ | ✓ |
| "delete" | remove | ✗ | ✓ |

**Comment by phalt** [comment]
Are Links supposed to be extendable? Can I create more than one "action" Link on a Document that performs a different action. This would allow me to self-describe my Document and the actions available on it to the service reading it.

**Comment by lovelydinosaur** [comment]
> Can I create more than one "action" Link on a Document that performs a different action.

Yes. The transition specifies the behavior of how the document transforms, but doesn't imply anything about the semantics of the transformation.

The name of the key that the link is given implies (softly) the semantics.
